import * as z from 'zod'

/*
 * Payload fixtures for the schema tests.
 *
 * These are SYNTHETIC — generated by walking the schema — rather than captured
 * from a device, which is the repo standard and the better source. They are
 * adequate here because these tests compare two parsers against *each other*
 * over the same inputs (does compiling, or memoising the derived schema, change
 * the result?), so what matters is that the corpus covers the full shape of
 * every model, not that it reproduces a real device's values.
 *
 * Anything asserting on device semantics rather than parser equivalence should
 * use a real capture, with a note on the device state it was taken in.
 */

interface ZodDef {
	type: string
	shape?: Record<string, unknown>
	element?: unknown
	items?: unknown[]
	innerType?: unknown
	options?: unknown[]
	values?: unknown[]
	entries?: Record<string, unknown>
	checks?: unknown[]
	format?: string
}

function defOf(schema: unknown): ZodDef | undefined {
	return (schema as { _zod?: { def?: ZodDef } })?._zod?.def
}

function numericBounds(def: ZodDef): { min: number | null; max: number | null; isInt: boolean } {
	let min: number | null = null
	let max: number | null = null
	let isInt = def.format === 'safeint'
	for (const check of def.checks ?? []) {
		const d = (check as { _zod?: { def?: { check?: string; value?: number; inclusive?: boolean; format?: string } } })
			?._zod?.def
		if (!d) continue
		if (d.check === 'greater_than' && d.value !== undefined) min = d.inclusive ? d.value : d.value + 1
		if (d.check === 'less_than' && d.value !== undefined) max = d.inclusive ? d.value : d.value - 1
		if (d.format === 'safeint') isInt = true
	}
	return { min, max, isInt }
}

/** Build a value that satisfies `schema`, by walking its definition. */
export function buildPayload(schema: unknown): unknown {
	const def = defOf(schema)
	if (!def) return undefined
	switch (def.type) {
		case 'object': {
			const out: Record<string, unknown> = {}
			for (const [key, value] of Object.entries(def.shape ?? {})) out[key] = buildPayload(value)
			return out
		}
		case 'array':
			return [buildPayload(def.element), buildPayload(def.element)]
		case 'tuple':
			return (def.items ?? []).map((item) => buildPayload(item))
		case 'string': {
			// The only constrained string in these schemas is the MAC address
			const constrained = (def.checks ?? []).some(
				(c) => (c as { _zod?: { def?: { pattern?: unknown; format?: unknown } } })?._zod?.def?.pattern !== undefined,
			)
			return constrained ? '00:11:22:33:44:55' : 'str'
		}
		case 'number': {
			const { min, max, isInt } = numericBounds(def)
			if (min !== null && max !== null) {
				const mid = (min + max) / 2
				return isInt ? Math.round(mid) : mid
			}
			if (min !== null) return min
			if (max !== null) return max
			return isInt ? 1 : 1
		}
		case 'boolean':
			return true
		case 'literal':
			return def.values?.[0]
		case 'enum':
			return Object.values(def.entries ?? {})[0]
		case 'nullable':
		case 'null':
		case 'any':
		case 'unknown':
			return null
		case 'optional':
		case 'nonoptional':
		case 'default':
			return buildPayload(def.innerType)
		case 'union':
			return buildPayload(def.options?.[0])
		case 'record':
			return {}
		default:
			return undefined
	}
}

/**
 * Deterministic pruner: drops object keys and array elements to produce the
 * arbitrarily-shaped partial payloads the device sends for a partial update.
 */
export function pruneDeterministic(value: unknown, seed: number, dropRate = 0.5): unknown {
	let state = seed
	const next = () => (state = (state * 1103515245 + 12345) & 0x7fffffff) / 0x7fffffff

	const walk = (v: unknown): unknown => {
		if (Array.isArray(v)) return v.filter(() => next() > 0.3).map(walk)
		if (v !== null && typeof v === 'object') {
			const out: Record<string, unknown> = {}
			for (const [k, val] of Object.entries(v)) if (next() > dropRate) out[k] = walk(val)
			return out
		}
		return v
	}
	return walk(value)
}

/** A corpus of partial payloads for one model: whole, empty, per-top-level-key, and pruned. */
export function partialPayloadCorpus(schema: z.ZodType): unknown[] {
	const full = buildPayload(schema) as Record<string, unknown>
	const corpus: unknown[] = [full, {}]
	for (const key of Object.keys(full)) corpus.push({ [key]: full[key] })
	for (let seed = 1; seed <= 40; seed++) corpus.push(pruneDeterministic(full, seed))
	return corpus
}

/** Serialise a parse result so two parsers can be compared exactly, successes and failures alike. */
export function serialiseResult(result: z.ZodSafeParseResult<unknown>): string {
	return result.success
		? `ok:${JSON.stringify(result.data)}`
		: `err:${result.error.issues.map((i) => `${i.path.join('.')}:${i.code}`).join('|')}`
}
